/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doanhttt;
//1092 698
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class MainFrame extends javax.swing.JFrame {
    int x,y;
    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
        DesktopPane.add(new DKMH()).setVisible(true);
//        btnQLDK.setEnabled(false);
//        btnQLHP.setEnabled(false);
//        btnTHONGKE.setEnabled(false);
//        btnQLTK.setEnabled(false);
    }
    class panelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d =(Graphics2D)g;
            int width=getWidth();
            int height=getHeight();
            Color color1=new Color(0, 204, 255);
            Color color2 = Color.GREEN;
            GradientPaint gp = new GradientPaint(0, 0, color1, 180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    public void ShowMain(){
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelButton = new panelGradient();
        btnDKMH = new javax.swing.JButton();
        btnQLDK = new javax.swing.JButton();
        btnQLHP = new javax.swing.JButton();
        btnTHONGKE = new javax.swing.JButton();
        btnQLTK = new javax.swing.JButton();
        jPanel2 = new panelGradient();
        label_exit = new javax.swing.JLabel();
        DesktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnDKMH.setBackground(new java.awt.Color(255, 0, 51));
        btnDKMH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDKMH.setText("ĐĂNG KÝ MÔN HỌC");
        btnDKMH.setBorder(null);
        btnDKMH.setBorderPainted(false);
        btnDKMH.setContentAreaFilled(false);
        btnDKMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDKMHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDKMHMouseExited(evt);
            }
        });
        btnDKMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDKMHActionPerformed(evt);
            }
        });

        btnQLDK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQLDK.setText("QUẢN LÝ ĐKMH");
        btnQLDK.setBorder(null);
        btnQLDK.setBorderPainted(false);
        btnQLDK.setContentAreaFilled(false);
        btnQLDK.setOpaque(false);
        btnQLDK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLDKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLDKMouseExited(evt);
            }
        });
        btnQLDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDKActionPerformed(evt);
            }
        });

        btnQLHP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQLHP.setText("QUẢN LÝ HỌC PHÍ");
        btnQLHP.setBorder(null);
        btnQLHP.setBorderPainted(false);
        btnQLHP.setContentAreaFilled(false);
        btnQLHP.setOpaque(false);
        btnQLHP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLHPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLHPMouseExited(evt);
            }
        });
        btnQLHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHPActionPerformed(evt);
            }
        });

        btnTHONGKE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTHONGKE.setText("THỐNG KÊ");
        btnTHONGKE.setBorder(null);
        btnTHONGKE.setBorderPainted(false);
        btnTHONGKE.setContentAreaFilled(false);
        btnTHONGKE.setOpaque(false);
        btnTHONGKE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTHONGKEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTHONGKEMouseExited(evt);
            }
        });
        btnTHONGKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHONGKEActionPerformed(evt);
            }
        });

        btnQLTK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQLTK.setText("QUẢN LÝ TÀI KHOẢN");
        btnQLTK.setBorder(null);
        btnQLTK.setBorderPainted(false);
        btnQLTK.setContentAreaFilled(false);
        btnQLTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLTKMouseExited(evt);
            }
        });
        btnQLTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDKMH, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(btnQLDK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTHONGKE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnDKMH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQLDK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQLHP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTHONGKE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        label_exit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_exit.setForeground(new java.awt.Color(255, 0, 0));
        label_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_exit.setText("X");
        label_exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_exit.setVerifyInputWhenFocusTarget(false);
        label_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_exitMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(label_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        DesktopPane.setBackground(new java.awt.Color(255, 255, 255));
        DesktopPane.setPreferredSize(new java.awt.Dimension(1062, 683));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1102, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseEntered
        // TODO add your handling code here:
        label_exit.setBackground(Color.red);
    }//GEN-LAST:event_label_exitMouseEntered

    private void label_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_label_exitMouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int xx=evt.getXOnScreen();
        int yy=evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btnDKMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDKMHActionPerformed
        // TODO add your handling code here:
        DesktopPane.removeAll();
        DesktopPane.add(new DKMH()).setVisible(true);
    }//GEN-LAST:event_btnDKMHActionPerformed

    private void btnDKMHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDKMHMouseEntered
        // TODO add your handling code here:
        btnDKMH.setForeground(Color.red);
    }//GEN-LAST:event_btnDKMHMouseEntered

    private void btnDKMHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDKMHMouseExited
        // TODO add your handling code here:        btnDKMH.setForeground(Color.red);
        btnDKMH.setForeground(null);

    }//GEN-LAST:event_btnDKMHMouseExited

    private void btnQLDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDKActionPerformed
        // TODO add your handling code here:
        DesktopPane.removeAll();
        DesktopPane.add(new QuanLyDKMH()).setVisible(true);
    }//GEN-LAST:event_btnQLDKActionPerformed

    private void btnTHONGKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHONGKEActionPerformed
        // TODO add your handling code here:
        DesktopPane.removeAll();
        DesktopPane.add(new ThongKe()).setVisible(true);
    }//GEN-LAST:event_btnTHONGKEActionPerformed

    private void btnQLHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHPActionPerformed
        // TODO add your handling code here:
        DesktopPane.removeAll();
        DesktopPane.add(new QuanLyHocPhi()).setVisible(true);
    }//GEN-LAST:event_btnQLHPActionPerformed

    private void btnQLDKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLDKMouseEntered
        // TODO add your handling code here:
        btnQLDK.setForeground(Color.red);
    }//GEN-LAST:event_btnQLDKMouseEntered

    private void btnQLDKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLDKMouseExited
        // TODO add your handling code here:
        btnQLDK.setForeground(null);

    }//GEN-LAST:event_btnQLDKMouseExited

    private void btnQLHPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLHPMouseEntered
        // TODO add your handling code here:
        btnQLHP.setForeground(Color.red);

    }//GEN-LAST:event_btnQLHPMouseEntered

    private void btnQLHPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLHPMouseExited
        // TODO add your handling code here:
        btnQLHP.setForeground(null);

    }//GEN-LAST:event_btnQLHPMouseExited

    private void btnTHONGKEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTHONGKEMouseEntered
        // TODO add your handling code here:
        btnTHONGKE.setForeground(Color.red);

    }//GEN-LAST:event_btnTHONGKEMouseEntered

    private void btnTHONGKEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTHONGKEMouseExited
        // TODO add your handling code here:
        btnTHONGKE.setForeground(null);

    }//GEN-LAST:event_btnTHONGKEMouseExited

    private void btnQLTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLTKMouseEntered
        // TODO add your handling code here:
        btnQLTK.setForeground(Color.red);
    }//GEN-LAST:event_btnQLTKMouseEntered

    private void btnQLTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLTKMouseExited
        // TODO add your handling code here:
        btnQLTK.setForeground(null);

    }//GEN-LAST:event_btnQLTKMouseExited

    private void btnQLTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTKActionPerformed
        // TODO add your handling code here:
        DesktopPane.removeAll();
        DesktopPane.add(new QLTK()).setVisible(true);
    }//GEN-LAST:event_btnQLTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JButton btnDKMH;
    private javax.swing.JButton btnQLDK;
    private javax.swing.JButton btnQLHP;
    private javax.swing.JButton btnQLTK;
    private javax.swing.JButton btnTHONGKE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_exit;
    private javax.swing.JPanel panelButton;
    // End of variables declaration//GEN-END:variables
}
