/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package doanhttt;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author DELL
 */
public class ThongKe extends javax.swing.JInternalFrame {

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
        BasicInternalFrameUI BI = (BasicInternalFrameUI)this.getUI();
        BI.setNorthPane(null);
        createChart1();
        createChart2();

    }
    class panelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d =(Graphics2D)g;
            int width=getWidth();
            int height=getHeight();
            Color color1=new Color(0, 204, 255);
            Color color2 =Color.GREEN;
            GradientPaint gp = new GradientPaint(0, 0, color1, 180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    public void createChart1(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(120, "", "Chủ nghĩa xã hội");
        dataset.setValue(40, "", "GDQPAN III");
        dataset.setValue(80, "", "Triết Mác-Lênin");
        JFreeChart chart = ChartFactory.createBarChart("Thống kê môn mở trong học kỳ", "Môn học", "Số lượng đky", dataset,PlotOrientation.HORIZONTAL,false,false,false);
        CategoryPlot catplot = chart.getCategoryPlot();
        catplot.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame("Thống kê môn mở trong học kỳ", chart);
        frame.setVisible(true);
        frame.setSize(1280, 720);
        

    }
    public void createChart2(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(60, "", "Nhóm lớp 1");
        dataset.setValue(120, "", "Nhóm lớp 2");
        dataset.setValue(20, "", "Nhóm lớp 3");
        JFreeChart chart = ChartFactory.createBarChart("Thống kê nhóm lớp được chọn trong học kỳ", "", "", dataset,PlotOrientation.HORIZONTAL,false,false,false);
        CategoryPlot catplot = chart.getCategoryPlot();
        catplot.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame("Thống kê nhóm lớp được chọn trong học kỳ", chart);
        frame.setVisible(true);
        frame.setSize(1280, 720);
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new panelGradient();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1106, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
